name: "Zinguo Bathroom Heater"
version: "1.0.0"
slug: "zinguo_bathroom_heater"
description: "Zinguo Smart Bathroom Fan Integration with secure credential storage"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: "application"
boot: "auto"
host_network: false
options: {}
schema: {}
image: "ghcr.io/jyz0501/hassio-zinguo-{arch}"
